### ISSUE TITLE
use toml config in manage.py

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rides-blueprint#40]
Problem: 

- CLI with `--db-url` is very long - need shorten the call 
-  need one place for defaults like `step_km` and `search_radius`, remove hard-coded defaults

Proposal:

- use `postgres.toml` in potion like `--config postgres.toml`

Toml sample:

```toml
db_url = "postgresql+pg8000://scott:tiger@localhost:5432/rider_db"
step_km = 2.5
search_radius = 3.5
```

Todo:

- make `test_config()` command that will demostarte use of config file

Note:
- we currently use `./temp/db.sqlite` as default database, should probably be `sqlite.toml`
- slightly complicated use of toml [here](https://github.com/epogrebnyak/rides-blueprint/blob/package_0_2_0_experimental_features/experimental/jobs.py)
